### ISSUE TITLE
存在遍历删除数组引发的异常

### ISSUE THREAD

**Issue by DuDuLuuu** [rnkrsoft/Bopomofo4j#3]
`
例子:
Bopomofo4j.pinyin("心宽体胖", ToneType.WITHOUT_TONE.getCode(), true, false, "")

代码:
for (int k = 0; k < data.getOffset(); k++) {
                            result.remove(i - data.getOffset() + k);
                            types.remove(i - data.getOffset() + k);
                        }

异常:
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.remove(ArrayList.java:496)
	at com.rnkrsoft.bopomofo4j.sandbox.v100.LocalKernel.pinyin(LocalKernel.java:52)
`

**Comment by rnkrsoft** [comment]
已修复
